// Code generated by Fern. DO NOT EDIT.

package comments

import (
    core "pentagi/pkg/observability/langfuse/api/core"
    internal "pentagi/pkg/observability/langfuse/api/internal"
    context "context"
    api "pentagi/pkg/observability/langfuse/api"
    option "pentagi/pkg/observability/langfuse/api/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

// Get all comments
func (c *Client) Get(
    ctx context.Context,
    request *api.CommentsGetRequest,
    opts ...option.RequestOption,
) (*api.GetCommentsResponse, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
func (c *Client) Create(
    ctx context.Context,
    request *api.CreateCommentRequest,
    opts ...option.RequestOption,
) (*api.CreateCommentResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a comment by id
func (c *Client) GetByID(
    ctx context.Context,
    request *api.CommentsGetByIDRequest,
    opts ...option.RequestOption,
) (*api.Comment, error){
    response, err := c.WithRawResponse.GetByID(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

