// Code generated by Fern. DO NOT EDIT.

package api

import (
    internal "pentagi/pkg/observability/langfuse/api/internal"
    core "pentagi/pkg/observability/langfuse/api/core"
)


var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
    400: func(apiError *core.APIError) error{
        return &BadRequestError{
            APIError: apiError,
        }
    },
    401: func(apiError *core.APIError) error{
        return &UnauthorizedError{
            APIError: apiError,
        }
    },
    403: func(apiError *core.APIError) error{
        return &ForbiddenError{
            APIError: apiError,
        }
    },
    404: func(apiError *core.APIError) error{
        return &NotFoundError{
            APIError: apiError,
        }
    },
    405: func(apiError *core.APIError) error{
        return &MethodNotAllowedError{
            APIError: apiError,
        }
    },
    503: func(apiError *core.APIError) error{
        return &ServiceUnavailableError{
            APIError: apiError,
        }
    },
}

