// Code generated by Fern. DO NOT EDIT.

package score

import (
    core "pentagi/pkg/observability/langfuse/api/core"
    internal "pentagi/pkg/observability/langfuse/api/internal"
    context "context"
    api "pentagi/pkg/observability/langfuse/api"
    option "pentagi/pkg/observability/langfuse/api/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

// Create a score (supports both trace and session scores)
func (c *Client) Create(
    ctx context.Context,
    request *api.CreateScoreRequest,
    opts ...option.RequestOption,
) (*api.CreateScoreResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Delete a score (supports both trace and session scores)
func (c *Client) Delete(
    ctx context.Context,
    request *api.ScoreDeleteRequest,
    opts ...option.RequestOption,
) error{
    _, err := c.WithRawResponse.Delete(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return err
    }
    return nil
}

