// Code generated by Fern. DO NOT EDIT.

package datasetitems

import (
    core "pentagi/pkg/observability/langfuse/api/core"
    internal "pentagi/pkg/observability/langfuse/api/internal"
    context "context"
    api "pentagi/pkg/observability/langfuse/api"
    option "pentagi/pkg/observability/langfuse/api/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

// Get dataset items
func (c *Client) List(
    ctx context.Context,
    request *api.DatasetItemsListRequest,
    opts ...option.RequestOption,
) (*api.PaginatedDatasetItems, error){
    response, err := c.WithRawResponse.List(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Create a dataset item
func (c *Client) Create(
    ctx context.Context,
    request *api.CreateDatasetItemRequest,
    opts ...option.RequestOption,
) (*api.DatasetItem, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a dataset item
func (c *Client) Get(
    ctx context.Context,
    request *api.DatasetItemsGetRequest,
    opts ...option.RequestOption,
) (*api.DatasetItem, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Delete a dataset item and all its run items. This action is irreversible.
func (c *Client) Delete(
    ctx context.Context,
    request *api.DatasetItemsDeleteRequest,
    opts ...option.RequestOption,
) (*api.DeleteDatasetItemResponse, error){
    response, err := c.WithRawResponse.Delete(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

