simple:
  model: "kimi-k2-turbo-preview"
  temperature: 0.6
  n: 1
  max_tokens: 8192
  price:
    input: 1.15
    output: 8.0

simple_json:
  model: "kimi-k2-turbo-preview"
  temperature: 0.6
  n: 1
  max_tokens: 4096
  json: true
  price:
    input: 1.15
    output: 8.0

primary_agent:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 16384
  price:
    input: 0.6
    output: 3.0

assistant:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 16384
  price:
    input: 0.6
    output: 3.0

generator:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 32768
  price:
    input: 0.6
    output: 3.0

refiner:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 20480
  price:
    input: 0.6
    output: 3.0

adviser:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 8192
  price:
    input: 0.6
    output: 3.0

reflector:
  model: "kimi-k2-0905-preview"
  temperature: 0.7
  n: 1
  max_tokens: 4096
  price:
    input: 0.6
    output: 2.5

searcher:
  model: "kimi-k2-0905-preview"
  temperature: 0.7
  n: 1
  max_tokens: 4096
  price:
    input: 0.6
    output: 2.5

enricher:
  model: "kimi-k2-0905-preview"
  temperature: 0.7
  n: 1
  max_tokens: 4096
  price:
    input: 0.6
    output: 2.5

coder:
  model: "kimi-k2.5"
  temperature: 1.0
  n: 1
  max_tokens: 20480
  price:
    input: 0.6
    output: 3.0

installer:
  model: "kimi-k2-turbo-preview"
  temperature: 0.7
  n: 1
  max_tokens: 16384
  price:
    input: 1.15
    output: 8.0

pentester:
  model: "kimi-k2-turbo-preview"
  temperature: 0.8
  n: 1
  max_tokens: 16384
  price:
    input: 1.15
    output: 8.0
