simple:
  model: gemini-3.1-flash-lite-preview
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 8192
  price:
    input: 0.25
    output: 1.5
    cache_read: 0.025

simple_json:
  model: gemini-3.1-flash-lite-preview
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 4096
  json: true
  price:
    input: 0.25
    output: 1.5
    cache_read: 0.025

primary_agent:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 16384
  reasoning:
    effort: medium
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

assistant:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 16384
  reasoning:
    effort: medium
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

generator:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 32768
  reasoning:
    effort: high
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

refiner:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 20480
  reasoning:
    effort: medium
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

adviser:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 8192
  reasoning:
    effort: medium
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

reflector:
  model: gemini-3-flash-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 4096
  price:
    input: 0.5
    output: 3.0
    cache_read: 0.05

searcher:
  model: gemini-3-flash-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 8192
  price:
    input: 0.5
    output: 3.0
    cache_read: 0.05

enricher:
  model: gemini-3-flash-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 4096
  price:
    input: 0.5
    output: 3.0
    cache_read: 0.05

coder:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 20480
  reasoning:
    effort: low
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2

installer:
  model: gemini-3-flash-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 16384
  reasoning:
    effort: low
  price:
    input: 0.5
    output: 3.0
    cache_read: 0.05

pentester:
  model: gemini-3.1-pro-preview
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 8192
  reasoning:
    effort: low
  price:
    input: 2.0
    output: 12.0
    cache_read: 0.2
